// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjYYokOK6ShsjFI7Pkqja_xVZgxNhXNqE',
    appId: '1:747484650864:web:d4c54007ed6a070b2203b5',
    messagingSenderId: '747484650864',
    projectId: 'sdjhinata',
    authDomain: 'sdjhinata.firebaseapp.com',
    storageBucket: 'sdjhinata.firebasestorage.app',
    measurementId: 'G-NM34VLFJJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwIKLBTjs0oHHSXd1fFwpmePBJzpM-qCc',
    appId: '1:747484650864:android:1d4858cd311d95ec2203b5',
    messagingSenderId: '747484650864',
    projectId: 'sdjhinata',
    storageBucket: 'sdjhinata.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf8dJu7uTx41c892zo-RaBqk5kOZgYgQo',
    appId: '1:747484650864:ios:0781abb150f6854f2203b5',
    messagingSenderId: '747484650864',
    projectId: 'sdjhinata',
    storageBucket: 'sdjhinata.firebasestorage.app',
    iosBundleId: 'com.example.sjdapp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf8dJu7uTx41c892zo-RaBqk5kOZgYgQo',
    appId: '1:747484650864:ios:0781abb150f6854f2203b5',
    messagingSenderId: '747484650864',
    projectId: 'sdjhinata',
    storageBucket: 'sdjhinata.firebasestorage.app',
    iosBundleId: 'com.example.sjdapp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjYYokOK6ShsjFI7Pkqja_xVZgxNhXNqE',
    appId: '1:747484650864:web:72e5b01b0f0e2d052203b5',
    messagingSenderId: '747484650864',
    projectId: 'sdjhinata',
    authDomain: 'sdjhinata.firebaseapp.com',
    storageBucket: 'sdjhinata.firebasestorage.app',
    measurementId: 'G-MBER8NB75K',
  );
}
